In [1]:
from nba_api.stats.endpoints import playergamelog
from nba_api.stats.static import players
import pandas as pd

# Obtener ID de jugador
player_dict = players.get_players()
player_id = [player for player in player_dict if player['full_name'] == 'Anthony Davis'][0]['id']

# Obtener estadísticas de juegos
gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024')
print(gamelog)

<nba_api.stats.endpoints.playergamelog.PlayerGameLog object at 0x0000024A2CADF260>

In [2]:
df = pd.DataFrame(player_dict)
df

           id            full_name first_name     last_name  is_active
0       76001       Alaa Abdelnaby       Alaa     Abdelnaby      False
1       76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz      False
2       76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar      False
3          51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf      False
4        1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad      False
...       ...                  ...        ...           ...        ...
5029  1627826          Ivica Zubac      Ivica         Zubac       True
5030    78650           Matt Zunic       Matt         Zunic      False
5031  1641783     Tristan da Silva    Tristan      da Silva       True
5032  1628427        Vlatko Čančar     Vlatko        Čančar       True
5033   203967          Dario Šarić      Dario         Šarić       True

[5034 rows x 5 columns]

In [3]:
from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.static import players, teams
import pandas as pd

# Obtener ID del jugador
player_dict = players.get_players()
player_id = [player for player in player_dict if player['full_name'] == 'LeBron James'][0]['id']

# Obtener ID del equipo
team_dict = teams.get_teams()
team_id = [team for team in team_dict if team['full_name'] == 'Golden State Warriors'][0]['id']

# Primero obtener todos los juegos del jugador
gamefinder = leaguegamefinder.LeagueGameFinder(
    player_or_team_abbreviation='P',  # 'P' para jugador, 'T' para equipo
    player_id_nullable=player_id
)

# Convertir a DataFrame y filtrar por equipo oponente
games = gamefinder.get_data_frames()[0]
games_vs_team = games[games['MATCHUP'].str.contains('GSW')]  # Filtramos juegos contra Golden State

# Si quieres ver las estadísticas promedio contra ese equipo
#stats_mean = games_vs_team.mean()

# Ver estadísticas específicas
print(f"Juegos contra Golden State Warriors:")
games_vs_team[['GAME_DATE', 'MATCHUP', 'PTS', 'AST', 'REB', 'STL', 'BLK']]
games_vs_team

Juegos contra Golden State Warriors:

,SEASON_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
3,12024,2544,LeBron James,1610612747,LAL,Los Angeles Lakers,0012400056,2024-10-15,LAL vs. GSW,L,...,NaN,0,2,2,4,0,0,3,0,-13.0
19,22023,2544,LeBron James,1610612747,LAL,Los Angeles Lakers,0022301155,2024-04-09,LAL vs. GSW,L,...,0.800,1,6,7,11,2,0,4,0,-6.0
29,22023,2544,LeBron James,1610612747,LAL,Los Angeles Lakers,0022300973,2024-03-16,LAL vs. GSW,L,...,0.875,3,5,8,9,1,1,4,1,-6.0
47,22023,2544,LeBron James,1610612747,LAL,Los Angeles Lakers,0022300650,2024-01-27,LAL @ GSW,W,...,1.000,1,19,20,12,0,0,3,2,-6.0
91,12023,2544,LeBron James,1610612747,LAL,Los Angeles Lakers,0012300034,2023-10-13,LAL vs. GSW,L,...,0.500,0,2,2,5,0,0,2,0,-9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,22005,2544,LeBron James,1610612739,CLE,Cleveland Cavaliers,0020500575,2006-01-20,CLE @ GSW,L,...,0.667,1,8,9,6,0,0,6,3,-9.0
1788,22004,2544,LeBron James,1610612739,CLE,Cleveland Cavaliers,0020400591,2005-01-22,CLE @ GSW,W,...,1.000,1,11,12,10,1,1,3,1,19.0
1820,22004,2544,LeBron James,1610612739,CLE,Cleveland Cavaliers,0020400096,2004-11-15,CLE vs. GSW,W,...,0.750,2,10,12,4,2,1,1,1,15.0
1835,22003,2544,LeBron James,1610612739,CLE,Cleveland Cavaliers,0020301102,2004-04-03,CLE vs. GSW,L,...,0.636,3,5,8,10,1,1,3,1,-3.0
1869,22003,2544,LeBron James,1610612739,CLE,Cleveland Cavaliers,0020300556,2004-01-15,CLE @ GSW,L,...,0.846,2,4,6,6,3,0,2,0,-14.0

In [4]:
from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.static import players, teams
import pandas as pd
import numpy as np

In [5]:
from nba_api.stats.static import players

def buscar_jugador(nombre_parcial):
    """
    Busca jugadores que contengan el texto especificado en su nombre.
    
    Args:
        nombre_parcial (str): Parte del nombre a buscar (no sensitivo a mayúsculas)
        
    Returns:
        DataFrame: Jugadores encontrados con su información
    """
    try:
        # Obtener lista de jugadores
        todos_jugadores = players.get_players()
        
        # Filtrar jugadores que contengan el texto en su nombre
        jugadores_encontrados = [
            jugador for jugador in todos_jugadores 
            if nombre_parcial.lower() in jugador['full_name'].lower()
        ]
        
        if not jugadores_encontrados:
            return "No se encontraron jugadores con ese nombre."
        
        # Crear DataFrame con la información relevante
        df_jugadores = pd.DataFrame(jugadores_encontrados)[
            ['full_name', 'first_name', 'last_name', 'is_active']
        ]
        
        # Renombrar columnas
        df_jugadores.columns = ['Nombre Completo', 'Nombre', 'Apellido', 'Activo']
        
        # Ordenar por estado (activo/retirado) y nombre
        df_jugadores = df_jugadores.sort_values(['Activo', 'Nombre Completo'], 
                                              ascending=[False, True])
        
        return df_jugadores
        
    except Exception as e:
        return f"Error en la búsqueda: {str(e)}"

# Ejemplo de uso:
# buscar_jugador("davis")

In [6]:
from nba_api.stats.static import teams

def buscar_equipo(nombre_parcial):
    """
    Busca equipos que contengan el texto especificado en su nombre.
    Muestra el nombre completo, abreviatura y ciudad.
    
    Args:
        nombre_parcial (str): Parte del nombre a buscar (no sensitivo a mayúsculas)
        
    Returns:
        DataFrame: Equipos encontrados con su información
    """
    try:
        # Obtener lista de equipos
        todos_equipos = teams.get_teams()
        
        # Filtrar equipos que contengan el texto en su nombre, ciudad o abreviatura
        equipos_encontrados = [
            equipo for equipo in todos_equipos 
            if nombre_parcial.lower() in equipo['full_name'].lower() or 
               nombre_parcial.lower() in equipo['city'].lower() or
               nombre_parcial.lower() in equipo['abbreviation'].lower()
        ]
        
        if not equipos_encontrados:
            return "No se encontraron equipos con ese nombre."
        
        # Crear DataFrame con la información relevante
        df_equipos = pd.DataFrame(equipos_encontrados)[
            ['full_name', 'abbreviation', 'city', 'state', 'nickname']
        ]
        
        # Renombrar columnas
        df_equipos.columns = ['Nombre Completo', 'Abreviatura', 'Ciudad', 'Estado', 'Apodo']
        
        return df_equipos
        
    except Exception as e:
        return f"Error en la búsqueda: {str(e)}"

# Ejemplos de uso:

In [7]:
def analizar_jugador_vs_equipo(nombre_jugador, equipo_rival, jugador_ausente=None, temporada='2023'):
    try:
        # Obtener ID del jugador
        player_dict = players.get_players()
        player_id = [player for player in player_dict if player['full_name'].lower() == nombre_jugador.lower()]
        if not player_id:
            return "Jugador no encontrado"
        player_id = player_id[0]['id']
        
        # Obtener juegos del jugador
        gamelog = playergamelog.PlayerGameLog(
            player_id=player_id,
            season=temporada
        ).get_data_frames()[0]
        
        # Preparar el DataFrame desde el inicio con todas las columnas necesarias
        games = gamelog[gamelog['MATCHUP'].str.contains(equipo_rival)].copy()
        if games.empty:
            return f"No se encontraron juegos contra {equipo_rival} en la temporada {temporada}"
            
        # Convertir fecha y agregar Local/Visita en una sola operación
        games = games.assign(
            GAME_DATE=pd.to_datetime(games['GAME_DATE'], format='mixed'),
            LOCAL_VISITOR=lambda x: x['MATCHUP'].apply(lambda m: 'Local' if 'vs.' in m else 'Visita')
        )
        
        # Manejar jugador ausente si se especifica
        if jugador_ausente:
            ausente_id = [p for p in player_dict if p['full_name'].lower() == jugador_ausente.lower()]
            if ausente_id:
                ausente_games = playergamelog.PlayerGameLog(
                    player_id=ausente_id[0]['id'],
                    season=temporada
                ).get_data_frames()[0]
                ausente_dates = pd.to_datetime(ausente_games['GAME_DATE'], format='mixed')
                games = games[~games['GAME_DATE'].isin(ausente_dates)]

        # Seleccionar y preparar las columnas finales
        cols = ['GAME_DATE', 'MATCHUP', 'LOCAL_VISITOR', 'PTS', 'REB', 'AST', 
                'FG3M', 'FG3A', 'STL', 'TOV', 'BLK', 'MIN']
        stats = games[cols].copy()
        
        # Calcular métricas adicionales
        stats = stats.assign(
            DOUBLE_DOUBLE=lambda x: ((x['PTS'] >= 10).astype(int) + 
                                   (x['REB'] >= 10).astype(int) + 
                                   (x['AST'] >= 10).astype(int) + 
                                   (x['STL'] >= 10).astype(int) + 
                                   (x['BLK'] >= 10).astype(int) >= 2).astype(int),
            TRIPLE_DOUBLE=lambda x: ((x['PTS'] >= 10).astype(int) + 
                                   (x['REB'] >= 10).astype(int) + 
                                   (x['AST'] >= 10).astype(int) + 
                                   (x['STL'] >= 10).astype(int) + 
                                   (x['BLK'] >= 10).astype(int) >= 3).astype(int),
            FG3_PCT=lambda x: np.where(x['FG3A'] > 0, (x['FG3M'] / x['FG3A']).round(3), 0)
        )
        
        # Convertir columnas numéricas a enteros
        num_cols = ['PTS', 'REB', 'AST', 'FG3M', 'FG3A', 'STL', 'TOV', 'BLK', 'MIN', 
                   'DOUBLE_DOUBLE', 'TRIPLE_DOUBLE']
        stats[num_cols] = stats[num_cols].astype(int)
        
        # Formatear fecha y ordenar
        stats['GAME_DATE'] = stats['GAME_DATE'].dt.strftime('%Y-%m-%d')
        stats = stats.sort_values('GAME_DATE', ascending=False).head(10)
        
        # Agregar fila de promedios
        promedios = stats.select_dtypes(include=[np.number]).mean().round(2)
        promedios_df = pd.DataFrame([{
            'GAME_DATE': 'PROMEDIO',
            'MATCHUP': '-',
            'LOCAL_VISITOR': '-',
            **promedios
        }])
        
        # Combinar y renombrar columnas
        stats = pd.concat([stats, promedios_df], ignore_index=True)
        stats.columns = ['Fecha', 'Rival', 'L/V', 'PTS', 'REB', 'AST', '3PM', '3PA', 
                        'ROB', 'PER', 'BLQ', 'MIN', 'DD', 'TD', '3P%']
        
        return stats
        
    except Exception as e:
        return f"Error al procesar los datos: {str(e)}"


def analizar_ultimos_partidos(nombre_jugador, equipo_rival=None, jugador_ausente=None, n_partidos=10):
    """
    Analiza los últimos N partidos de un jugador, opcionalmente filtrando por equipo rival.
    
    Args:
        nombre_jugador (str): Nombre del jugador
        equipo_rival (str, opcional): Abreviatura del equipo rival (ej: 'GSW', 'LAL')
        jugador_ausente (str, opcional): Nombre del jugador ausente para filtrar
        n_partidos (int, opcional): Número de últimos partidos a analizar (default 10)
    """
    try:
        # Obtener ID del jugador
        player_dict = players.get_players()
        player_id = [player for player in player_dict if player['full_name'].lower() == nombre_jugador.lower()]
        if not player_id:
            return "Jugador no encontrado"
        player_id = player_id[0]['id']
        
        # Obtener juegos de la temporada actual
        current_season = '2024'  # 2023-24
        gamelog_current = playergamelog.PlayerGameLog(
            player_id=player_id,
            season=current_season
        ).get_data_frames()[0]
        # Agregar columna de temporada
        gamelog_current['SEASON'] = '2023-24'
        
        # Obtener juegos de la temporada anterior
        previous_season = '2023'  # 2022-23
        gamelog_previous = playergamelog.PlayerGameLog(
            player_id=player_id,
            season=previous_season
        ).get_data_frames()[0]
        # Agregar columna de temporada
        gamelog_previous['SEASON'] = '2022-23'
        
        # Combinar los juegos de ambas temporadas
        gamelog = pd.concat([gamelog_current, gamelog_previous])
        
        # Preparar el DataFrame desde el inicio
        games = gamelog.copy()
        
        # Filtrar por equipo rival si se especifica
        if equipo_rival:
            games = games[games['MATCHUP'].str.contains(equipo_rival)]
            if games.empty:
                return f"No se encontraron partidos contra {equipo_rival}"
        
        # Convertir fecha y agregar Local/Visita en una sola operación
        games = games.assign(
            GAME_DATE=pd.to_datetime(games['GAME_DATE'], format='mixed'),
            LOCAL_VISITOR=lambda x: x['MATCHUP'].apply(lambda m: 'Local' if 'vs.' in m else 'Visita')
        )
        
        # Manejar jugador ausente si se especifica
        if jugador_ausente:
            ausente_id = [p for p in player_dict if p['full_name'].lower() == jugador_ausente.lower()]
            if ausente_id:
                # Obtener juegos del jugador ausente de ambas temporadas
                ausente_current = playergamelog.PlayerGameLog(
                    player_id=ausente_id[0]['id'],
                    season=current_season
                ).get_data_frames()[0]
                
                ausente_previous = playergamelog.PlayerGameLog(
                    player_id=ausente_id[0]['id'],
                    season=previous_season
                ).get_data_frames()[0]
                
                ausente_games = pd.concat([ausente_current, ausente_previous])
                ausente_dates = pd.to_datetime(ausente_games['GAME_DATE'], format='mixed')
                games = games[~games['GAME_DATE'].isin(ausente_dates)]

        # Seleccionar y preparar las columnas finales
        cols = ['GAME_DATE', 'MATCHUP', 'SEASON', 'LOCAL_VISITOR', 'PTS', 'REB', 'AST', 
                'FG3M', 'FG3A', 'STL', 'TOV', 'BLK', 'MIN']
        stats = games[cols].copy()
        
        # Calcular métricas adicionales
        stats = stats.assign(
            DOUBLE_DOUBLE=lambda x: ((x['PTS'] >= 10).astype(int) + 
                                   (x['REB'] >= 10).astype(int) + 
                                   (x['AST'] >= 10).astype(int) + 
                                   (x['STL'] >= 10).astype(int) + 
                                   (x['BLK'] >= 10).astype(int) >= 2).astype(int),
            TRIPLE_DOUBLE=lambda x: ((x['PTS'] >= 10).astype(int) + 
                                   (x['REB'] >= 10).astype(int) + 
                                   (x['AST'] >= 10).astype(int) + 
                                   (x['STL'] >= 10).astype(int) + 
                                   (x['BLK'] >= 10).astype(int) >= 3).astype(int),
            FG3_PCT=lambda x: np.where(x['FG3A'] > 0, (x['FG3M'] / x['FG3A']).round(3), 0)
        )
        
        # Convertir columnas numéricas a enteros
        num_cols = ['PTS', 'REB', 'AST', 'FG3M', 'FG3A', 'STL', 'TOV', 'BLK', 'MIN', 
                   'DOUBLE_DOUBLE', 'TRIPLE_DOUBLE']
        stats[num_cols] = stats[num_cols].astype(int)
        
        # Formatear fecha y ordenar
        stats['GAME_DATE'] = stats['GAME_DATE'].dt.strftime('%Y-%m-%d')
        stats = stats.sort_values('GAME_DATE', ascending=False).head(n_partidos)
        
        # Agregar fila de promedios
        promedios = stats.select_dtypes(include=[np.number]).mean().round(2)
        promedios_df = pd.DataFrame([{
            'GAME_DATE': 'PROMEDIO',
            'MATCHUP': '-',
            'SEASON': '-',
            'LOCAL_VISITOR': '-',
            **promedios
        }])
        
        # Combinar y renombrar columnas
        stats = pd.concat([stats, promedios_df], ignore_index=True)
        stats.columns = ['Fecha', 'Rival', 'Temporada', 'L/V', 'PTS', 'REB', 'AST', '3PM', '3PA', 
                        'ROB', 'PER', 'BLQ', 'MIN', 'DD', 'TD', '3P%']
        
        return stats
        
    except Exception as e:
        return f"Error al procesar los datos: {str(e)}"

In [8]:
print("Búsqueda por ciudad:")
print(buscar_equipo("clip"))

Búsqueda por ciudad:
        Nombre Completo Abreviatura       Ciudad      Estado     Apodo
0  Los Angeles Clippers         LAC  Los Angeles  California  Clippers

In [15]:
resultados = buscar_jugador("hield")
print(resultados)

     Nombre Completo   Nombre   Apellido  Activo
0        Buddy Hield    Buddy      Hield    True
1  Garland O'Shields  Garland  O'Shields   False

In [16]:
df = analizar_ultimos_partidos('Buddy Hield',n_partidos=15)
df

,Fecha,Rival,Temporada,L/V,PTS,REB,AST,3PM,3PA,ROB,PER,BLQ,MIN,DD,TD,3P%
0,2024-10-25,GSW @ UTA,2023-24,Visita,27.00,4.0,6.00,7.00,9.00,1.00,0.0,0.00,20.0,0.0,0.0,0.778
1,2024-10-23,GSW @ POR,2023-24,Visita,22.00,5.0,1.00,5.00,7.00,0.00,1.0,0.00,15.0,0.0,0.0,0.714
2,2024-04-14,PHI vs. BKN,2022-23,Local,19.00,7.0,5.00,4.00,10.00,1.00,1.0,0.00,22.0,0.0,0.0,0.400
3,2024-04-12,PHI vs. ORL,2022-23,Local,6.00,3.0,0.00,2.00,4.00,0.00,1.0,0.00,14.0,0.0,0.0,0.500
4,2024-04-09,PHI vs. DET,2022-23,Local,18.00,6.0,0.00,5.00,9.00,0.00,1.0,0.00,25.0,0.0,0.0,0.556
5,2024-04-07,PHI @ SAS,2022-23,Visita,10.00,2.0,3.00,2.00,5.00,1.00,2.0,0.00,20.0,0.0,0.0,0.400
6,2024-04-06,PHI @ MEM,2022-23,Visita,7.00,1.0,1.00,1.00,7.00,2.00,1.0,1.00,26.0,0.0,0.0,0.143
7,2024-04-04,PHI @ MIA,2022-23,Visita,2.00,2.0,0.00,0.00,4.00,0.00,0.0,0.00,12.0,0.0,0.0,0.000
8,2024-04-02,PHI vs. OKC,2022-23,Local,7.00,2.0,0.00,1.00,2.00,2.00,2.0,0.00,21.0,0.0,0.0,0.500
9,2024-03-31,PHI @ TOR,2022-23,Visita,13.00,3.0,3.00,3.00,5.00,0.00,3.0,1.00,22.0,0.0,0.0,0.600
10,2024-03-29,PHI @ CLE,2022-23,Visita,10.00,4.0,2.00,1.00,2.00,1.00,0.0,0.00,18.0,0.0,0.0,0.500
11,2024-03-27,PHI vs. LAC,2022-23,Local,17.00,3.0,1.00,3.00,7.00,0.00,1.0,1.00,26.0,0.0,0.0,0.429
12,2024-03-25,PHI @ SAC,2022-23,Visita,7.00,5.0,3.00,0.00,6.00,0.00,0.0,0.00,32.0,0.0,0.0,0.000
13,2024-03-24,PHI @ LAC,2022-23,Visita,9.00,4.0,2.00,3.00,6.00,0.00,1.0,0.00,23.0,0.0,0.0,0.500
14,2024-03-22,PHI @ LAL,2022-23,Visita,5.00,0.0,1.00,1.00,3.00,2.00,1.0,1.00,13.0,0.0,0.0,0.333
15,PROMEDIO,-,-,-,11.93,3.4,1.87,2.53,5.73,0.67,1.0,0.27,20.6,0.0,0.0,0.420

In [17]:
df = analizar_ultimos_partidos('Buddy Hield', 'LAC')   
df

,Fecha,Rival,Temporada,L/V,PTS,REB,AST,3PM,3PA,ROB,PER,BLQ,MIN,DD,TD,3P%
0,2024-03-27,PHI vs. LAC,2022-23,Local,17.00,3.00,1.00,3.0,7.00,0.0,1.00,1.00,26.00,0.0,0.0,0.429
1,2024-03-24,PHI @ LAC,2022-23,Visita,9.00,4.00,2.00,3.0,6.00,0.0,1.00,0.00,23.00,0.0,0.0,0.500
2,2023-12-18,IND vs. LAC,2022-23,Local,14.00,0.00,4.00,3.0,7.00,0.0,2.00,1.00,30.00,0.0,0.0,0.429
3,PROMEDIO,-,-,-,13.33,2.33,2.33,3.0,6.67,0.0,1.33,0.67,26.33,0.0,0.0,0.450